# Generated by Django 2.1.1 on 2018-11-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_id', models.IntegerField()),
                ('ip', models.CharField(max_length=20)),
                ('host_state', models.CharField(max_length=5)),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('port_state', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_id', models.IntegerField()),
                ('first_domain', models.CharField(max_length=67)),
                ('sub_domain', models.CharField(max_length=67, unique=True)),
                ('ip', models.CharField(max_length=20)),
                ('ip_addr', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_name', models.CharField(max_length=255)),
                ('main_host', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
