# Generated by Django 2.1.2 on 2019-03-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_cipdomain_ctarget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctarget',
            old_name='end_ip',
            new_name='c_ip',
        ),
        migrations.RemoveField(
            model_name='ctarget',
            name='start_ip',
        ),
    ]
