# Generated by Django 2.1.7 on 2019-03-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190325_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cipdomain',
            name='domain',
            field=models.CharField(max_length=67),
        ),
    ]
